version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  
  api-eventos:
    image: gabriel94dantas/api-eventos-image:latest
    depends_on:
      - broker
    hostname: api-eventos
    container_name: api-eventos
    ports:
      - 80:80
    environment:
      - BROKER_HOST=broker:29092

  cache:
    image: redis
    hostname: cache
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
  
  db:
    image: mysql:8.0
    container_name: mysql_signature   
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: poc_saga_signature
    ports:
     - '3306:3306'

  api-signature-doc:    
    image: lucashenrique01/api-signature-doc:1.3      
    depends_on:  
      - db
      - cache
      - broker
    container_name: api-signature-doc
    hostname: api-signature-doc
    environment:
      - BROKER_HOST=broker:29092
    ports:
     - '8080:8080'
  
  api-orchestrator:    
    image: lucashenrique01/api-orchestrator:1.2
    depends_on:  
      - db
      - cache
      - broker
    container_name: api-orchestrator
    hostname: api-orchestrator
    environment:
      - BROKER_HOST=broker:29092
      - REDIS_HOST=redis://cache:6379
    ports:
     - '8090:8090'

  api-create-doc:
     image: lucashenrique01/api-create-doc:1.0  
     container_name: api-create-doc
     hostname: api-create-doc
     environment:
       - MONGO_HOST=mongodb://mongo:27017
       - BROKER_HOST=broker:29092
  
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - 27017:27017
  
  flink_transformer:
    image: gabriel94dantas/flink-runner-poc-kappa:1.2
    depends_on:
      - broker
      - mongo
      - api-eventos
      - zookeeper
      - schema-registry
    container_name: flink_transformer
    hostname: flink_transformer
    environment:
      - BROKER_HOST=broker:29092
      - BROKER_HOST_CLOUDERA=broker:29092
      - MONGO_HOST=mongodb://mongo:27017

  apl-api-email-mocked:
    image: gabriel94dantas/poc-saga-email-mocked:1.0
    depends_on:
      - broker
    hostname: apl-api-email-mocked
    container_name: apl-api-email-mocked
    ports:
      - 88:88
    environment:
      - BROKER_HOST=broker:29092
